### ISSUE TITLE
tox.ini should use pip to install package

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid_zcml#14]
The current method of using python setup.py develop means you have to re-create the tox environment before you can re-run tests otherwise you get a nasty-gram about the Egg-link not being in the right location or something along those lines.

```
AssertionError: Egg-link /Users/xistence/Projects/pyramid_zcml does not match installed location of pyramid-zcml (at /Users/xistence/Projects/pyramid_zcml/.tox/py26/lib/python2.6/site-packages)
```

**Comment by mmerickel** [comment]
Fixed in #17.

**Comment by bertjwregeer** [comment]
#17 wasn't merged. And was not fixed in:

https://github.com/Pylons/pyramid_zcml/pull/24/files#diff-b91f3d5bd63fcd17221b267e851608e8R39

Further updates are required on top of #24

**Comment by fschulze** [comment]
Should be fixed now
