### ISSUE TITLE
No module named script.template with Pyramid 1.3

### ISSUE THREAD

**Issue by sirn** [Pylons/pyramid_zcml#2]
Errors:

    File "/[snip]/python2.7/site-packages/pyramid_zcml-0.8-py2.7.egg/pyramid_zcml/__init__.py", line 5, in <module>
        from paste.script.templates import Template
    ImportError: No module named script.templates

Steps to reproduce:

1. Create a new virtualenv and generate new pyramid application.
2. Follow the [instructions](http://docs.pylonsproject.org/projects/pyramid_zcml/en/latest/) in pyramid_zcml documentation.
3. `pserve development.ini`
4. Oops!

Since Pyramid 1.3 no longer have PasteScript as dependency yet pyramid_zcml is still using it thus the error after doing  `python setup.py` in a clean environment. I know this is solvable by install PasteScript by myself, but since the requirement is missing from pyramid_zcml, I guess this is a bug.

**Comment by tseaver** [comment]
Fixed in d9349bb9cf19bf7c65a31cf19f6372a24bf4eea2
