### ISSUE TITLE
AttributeError in pyramid_zcml with pyramid 1.8.0

### ISSUE THREAD

**Issue by papachoco** [Pylons/pyramid_zcml#22]
pyramid_zcml-1.0.0-py2.7.egg/pyramid_zcml/__init__.py", line 822

makes the following call

package_name, filename = self._split_spec(spec)

however pyramid 1.8.0 has removed that method

Carlos

**Comment by mmerickel** [comment]
It was removed as part of https://github.com/Pylons/pyramid/pull/2873. I'd just pull the impl into pyramid_zcml.

`pyramid.asset.resolve_asset_spec(spec, self.package_name)`

This is not a public API either but it's not in any danger of being removed.
