### ISSUE TITLE
Fix link on PyPI to correct version of docs

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid_zcml#25]
On [PyPI](https://pypi.python.org/pypi/pyramid_zcml), the link to the docs returns a 404.

> See http://docs.pylonsproject.org/projects/pyramid_zcml/dev/ for detailed documentation.

This should be:
http://docs.pylonsproject.org/projects/pyramid_zcml/en/latest/

**Comment by stevepiercy** [comment]
Not sure why this was closed. The link is still not correct.

**Comment by fschulze** [comment]
I closed it, because of your PR which will fix it for the next release. Unfortunately the "register" command is gone on PyPI, so one can't update the infos without a new release.

**Comment by stevepiercy** [comment]
Ah, OK. Thanks for the explanation. Closing, with the assumption that a release is coming soon.
