### ISSUE TITLE
Drop/Bump Python version support

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid_zcml#30]
Should support for Python:
1. 2.7 be dropped?
2. 3.4 be dropped?
3. 3.7 be added?
4. 3.8 be added?

_Originally posted by @fschulze in https://github.com/Pylons/pyramid_zcml/pull/29#issuecomment-606469176_

There have been changes to zope.interface and zope.schema 6.0.0 dropped Python 3.4 support, maybe zope.interface needs to be pinned for 3.4 because of that.

**Comment by bertjwregeer** [comment]
For now we should drop 3.4 at least, to fix build issues.

**Comment by bertjwregeer** [comment]
Fixed with #32
